# Generated by Django 4.2.4 on 2023-08-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarInStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=200, verbose_name='Производитель')),
                ('model', models.CharField(max_length=200, verbose_name='Модель')),
                ('car_body', models.CharField(blank=True, max_length=100, null=True, verbose_name='Кузов')),
                ('odometer', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Пробег')),
                ('fuel_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип топлива')),
                ('car_volume', models.CharField(blank=True, max_length=20, null=True, verbose_name='Объем')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год')),
                ('gearbox', models.CharField(blank=True, max_length=20, null=True, verbose_name='Коробка передач')),
                ('drive_unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Привод')),
                ('vin', models.CharField(blank=True, max_length=200, null=True, verbose_name='VIN')),
            ],
            options={
                'verbose_name': 'Авто в наличии',
                'verbose_name_plural': 'Авто в наличии',
            },
        ),
    ]
